name: imgflip_api
description: An API for Imgflip made in Dart. This package allows you to interact with the Imgflip API to create memes.
version: 1.0.0
repository: https://github.com/YarosMallorca/imgflip_api

environment:
  sdk: ^3.4.0

dependencies:
  http: ^1.2.1

dev_dependencies:
  lints: ^4.0.0
  mockito: ^5.4.4
  test: ^1.25.5
